services:
  - type: web
    name: myokr
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: myokr-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPL_ID
        sync: false
      - key: ISSUER_URL
        value: https://replit.com/oidc
      - key: REPLIT_DOMAINS
        sync: false

databases:
  - name: myokr-db
    databaseName: myokr
    user: myokr
